package AnalisadorLexico;

public enum TipoToken {

    IF, ELSE, WHILE, FOR, DO, BREAK, CONTINUE, RETURN, SWITCH, CASE,
    
    CLASS, INTERFACE, NEW, THIS, SUPER, EXTENDS, IMPLEMENTS, VOID,
    PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL,
    
    DECLARATIONS, ALGORITHM, ASSIGN_KW, TO, READ, PRINT, THEN, BEGIN, END,
    
    INT, FLOAT, STRING, BOOLEAN,
    
    IDENTIFIER, INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL, TRUE, FALSE,
    
    ASSIGN, ADD_ASSIGN, SUB_ASSIGN,
    
    PLUS, MINUS, MULT, DIV, MOD, INCREMENT, DECREMENT,
    
    EQUAL, NOT_EQUAL, GREATER, LESS, GREATER_EQUALS, LESS_EQUALS, AND, OR, NOT,
    
    COLON, SEMICOLON, COMMA, DOT,
    LPAREN, RPAREN,       
    LBRACE, RBRACE,       
    LBRACKET, RBRACKET,   
    
    ARROW, MATCH,
   
    EOF, ERROR
    
    
}