package AnalisadorLexico;

public enum TipoToken {

	IF, ELSE, WHILE, FOR, RETURN, DO, BREAK, CONTINUE,
	
	INT, FLOAT, STRING, BOOLEAN,
	
	IDENTIFIER, INT_LITERAL, STRING_LITERAL, TRUE, FALSE,
	
	ASSING, PLUS, MINUS, MULT, DIV, MOD, INCREMET, DECREMENT,
	
	EQUAL, NOT_EQUAL, GREATER, LESS, GREATER_EQUALS, LESS_EQUALS, AND, OR, NOT,
	
	ADD_ASSING, SUB_ASSING,
	
	COLON, SEMICOLON, COMMA, LPAREN, RPAREN, LBRACE, RBRACE,
	
	EOF, ERROR
}
